[project]
name = "py2-nostalgia"
version = "1.0.0"  # ready for production
description = "bottom text"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pytest>=6.9",
]
